# 接続先DB
# 接続先DB
spring.datasource.url=jdbc:h2:file:C:/Users/junji/test;AUTO_SERVER=TRUE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# H2 Console 有効化設定
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.h2.console.settings.web-allow-others=true

# ★【追加】JPA / Hibernate テーブル自動作成設定
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# SQLログの出力設定
spring.jpa.show-sql=true

# Spring Security の内部ログを出力
logging.level.org.springframework.security=DEBUG